### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by njmulsqb**
add comma to fix the syntax error

Signed-off-by: Najam Ul Saqib <najamulsaqib@tutamail.com>

### CODE REVIEW

**Review by psiinon — APPROVED** [review]

**Review by kingthorin — APPROVED** [review]

**Comment by thc202** [comment]
The commit/pull request description should have been other thing, this is not fixing a syntax error, the comma was added to a code comment (in any case the whole excerpt is not syntactically correct).

**Comment by kingthorin** [comment]
@njmulsqb looks like this bit will need further adjustment. I guess Simon and I didn’t analyze thoroughly enough.

**Comment by njmulsqb** [comment]
> @njmulsqb looks like this bit will need further adjustment. I guess Simon and I didn’t analyze thoroughly enough.

Sure, let me know whatever is required!

**Comment by thc202** [comment]
It does not require actual changes, was more for accurate commit description.

**Pull request merged**
