### PR TITLE
default will be http://zap/JSON but when ZAP_ENDPOINT env variable is…

### PR DESCRIPTION
**Pull request by stefan-sev**
… set then this will be the base url

### CODE REVIEW

**Comment by stefan-sev** [comment]
So this expects that zap is running in an docker container and I can access it under the name http://zap/JSON within the docker network. With this option i was able to define also a remote or locally running zap instance(e.g. http://localhost:8080/JSON). That was the basic usecase. Thanks for the fast response.

**Comment by psiinon** [comment]
This pull request **introduces 1 alert** when merging ca940dedd973415b81f6ea4e40a5205037f3d368 into e8cd42f54dd87c871078b12071114ee6178dcdb4 - [view on LGTM.com](https://lgtm.com/projects/g/zaproxy/zap-api-nodejs/rev/pr-a9a298e2744474abfb9e2b41e5277753d7196754)

**new alerts:**

* 1 for Implicit operand conversion

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by thc202** [comment]
OK, in that case it should be changed the value of the proxy not the `BASE` (which should always use the `zap` domain, to ensure the client requests are processed as ZAP API requests).

**Comment by stefan-sev** [comment]
Okay I tried to set the proxy to http://localhost:8080, but I was not able to run it. What proxy is in front of the zaproxy?

**Comment by thc202** [comment]
In this case the proxy is ZAP itself, the client connects to the proxy/ZAP then issues the `zap` requests.

 Could you provide more details about the problem, are there any errors?

**Comment by stefan-sev** [comment]
when I changed BASE=http://localhost:8080/JSON  I was able to execute the scan

**Comment by thc202** [comment]
The example is working fine here, is there anything in the ZAP logs?

**Comment by stefan-sev** [comment]
Now I manage to make it running as well. So I will close this thanks for the help

**Comment by thc202** [comment]
No problem, thanks for letting us know.

**Pull request closed without merging**
