### PR TITLE
Update Author Information in package.json

### PR DESCRIPTION
**Pull request by njmulsqb**

### CODE REVIEW

**Comment by kingthorin** [comment]
Please remove all the unrelated and unnecessary commits.

**Comment by njmulsqb** [comment]
The commits are interesting, I synced my fork and created this commit from Github web interface, only the commits are showing up, file changed section shows nothing but my recent change. Any idea why is that?

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
The default branch had old changes, the sync just merged the branches which keeps old changes. Better not work on the default branch, branch off instead.

**Comment by thc202** [comment]
Thank you!

**Comment by njmulsqb** [comment]
Thank you, the package.json file has outdated version information, can you update it to the newer version? @thc202

**Comment by thc202** [comment]
What's outdated specifically?

**Pull request merged**
