### PR TITLE
Add config for GitHub-native Dependabot

### PR DESCRIPTION
**Pull request by thc202**
Add configuration for NPM updates.

### CODE REVIEW

**Comment by thc202** [comment]
@kingthorin, @psiinon maybe instead of daily it could be weekly or monthly? These repos (same for zap-hud) are not released that often that require daily updates.

**Comment by psiinon** [comment]
We could try weekly to start with?

**Comment by kingthorin** [comment]
Weekly sounds good to me.

**Comment by thc202** [comment]
Updated to weekly and changed to WIP (pending agreement about the issue with the forks).

**Comment by thc202** [comment]
No longer WIP.

**Review by kingthorin — APPROVED** [review]

**Review by psiinon — APPROVED** [review]

**Pull request merged**
